-- AlterTable
ALTER TABLE "Actor" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "AuthorityRule" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Deal" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "MaterialObject" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "id" DROP DEFAULT;
